# Generated by Django 5.0.2 on 2024-07-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='main_memeber',
            field=models.BooleanField(default=False),
        ),
    ]
